### PR TITLE
fix initial tag computation

### LINKED ISSUE #9: Computed initial semver tag is invalid
Hi. I'm using the action on a new repo with no existing tags, and it's computing the following tag:

```Run craig-day/compute-tag@v13
Fetching existing tags. This may take a while on large repositories.
Tags fetch complete.
Computed the next tag as: v1.0.0.0
```

I would expect to see `v1.0.0`, or something with 3 numbers. AFAIK having 4 numbers is not valid semver.

The code seems to be appending an extra zero to all initial tags:

https://github.com/craig-day/compute-tag/blob/f621c5c68f308e49b10cd840d40301b8aead0349/action.js#L52

In case this is the intended behavior, can you explain why?

### PR DESCRIPTION
**Pull request by kzajac-zendesk**
When calling github action for first time we get wrong initial tag computed.
Examples:

- `INPUT_GITHUB_TOKEN=$(gh auth token) INPUT_TAG_FETCH_DEPTH=10 INPUT_VERSION_TYPE=major INPUT_VERSION_SCHEME=semantic GITHUB_REPOSITORY=test_repo`

gives 1.0.0.0 while expected version would be 1.0.0

- `INPUT_GITHUB_TOKEN=$(gh auth token) INPUT_TAG_FETCH_DEPTH=10 INPUT_VERSION_TYPE=major INPUT_VERSION_SCHEME=continuous GITHUB_REPOSITORY=test_repo`

gives v1.0 while expected version would be v1

resolves #9

### CODE REVIEW

File: action.js [hunk 1]
```diff
@@ -56,7 +56,7 @@ function initialTag(tag) {
   const suffix = core.getInput('prerelease_suffix')
   const newTag = isPrerelease ? `${tag}-${suffix}` : tag
 
-  return `${newTag}.0`
+  return `${newTag}`
```
Comment (craig-day) [inline action.js:59]: Just combine these, no need to template string the variable by itself. 

```js
return isPrerelease ? `${tag}-${suffix}` : tag
```

**Review by craig-day — CHANGES_REQUESTED** [review]
